baseURL = "https://fxlin0261.github.io/"
title = "fxlin0261's Blog"
theme = "PaperMod"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 70

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
author = "fxlin0261"
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
UseHugoToc = true
showtoc = true
tocopen = false
math = true

[taxonomies]
tag = "tags"
series = "series"

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 10

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 30

[[menu.main]]
name = "关于"
url = "/about/"
weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]